seed: 0
wandb:
  log: True
  dir: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\runs
  experiment_name: NAME
  entity: hofland-jeroen
  project: cc5k
  weights: model-egtpv2r8 # ID for reference hofland-jeroen/cc5k/{weights}:best
debugger:
  batches: False # number | False
  profiler: AdvancedProfiler # SimpleProfiler | AdvancedProfiler | False
  dir: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\debugging
  accelerator: False
  batch_tuner: False
  anomaly: False
model:
  name: CubiCasa # CubiCasa | CubiCasa21M
  input_slice: [21, 12, 11]
  loss: UncertaintyLoss # UncertaintyLoss | False
  weights: False # path | False
  watch: False
  init_weights: True
optimizer:
  name: adam
  lr: 0.001
  eps: 1e-08
  betas: [0.9, 0.999]
  patience: 10
mmd:
  enable: True
  latent_channels: 256 # 512 | 
  latent_transformation: nn.AdaptiveMaxPool2d((4, 4)) # nn.AdaptiveMaxPool2d((1, 1)) | nn.AdaptiveMaxPool2d((2, 2)) 
  lambda_constant: 0.1
  lambda_variable: False # False | number (higher > steeper)
  lambda_adaptive: False # False | True (learnable)
train:
  batch_size: 8
  accumulate_grad_batches: 1 # effective batch size = accumulate_grad_batches * batch_size
  resume: False # path | False 
  max_epochs: 1
  max_time:
    enable: False
    days: 0
    hours: 0
    minutes: 0
  debug:
    enable: True
    print: False
    train_batches: 25 # number | False
    val_batches: 25 # number | False
    test_batches: 66 # number | False
test:
  weights: False # path | False
  data: test_c.txt
  heatmap_threshold: 0.4
  experiment_variable: Lambda (C)
  experiment_measure: self.cfg.mmd.lambda_constant
  exclude_classes:
    enable: False
    rooms: [10] # [10: Garage]
    icons: [8, 9, 10] # [8: Fire Place, 9: Bathtub, 10: Chimney]
dataset:
  name: cubicasa
  num_workers: 2 # 10 (local) | 0.5 * cpus (cluster)
  format: txt # lmdb or txt
  augmentations: True
  original_size: True
  persistent_workers: True
  pin_memory: True
  grayscale: False
  overwrite: False
  save_samples: False
  load_samples: True
  scale: False
  image_size: 256
  val_size: False
  files:
    root: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\data\
    train: train_hqa_hq.txt
    val: val_hqa_hq.txt
    mmd:
      train: train_c.txt
      val: val_c.txt
    test: 
      d1: test_hqa.txt
      d2: test_hq.txt
      d3: test_c.txt