seed: 0
wandb:
  log: True
  dir: /tudelft.net/staff-umbrella/StudentsCVlab/jlhofland
  experiment_name: GRAY_100E_B20
  entity: hofland-jeroen
  project: cc5k
debugger:
  batches: False # number | False
  profiler: SimpleProfiler # SimpleProfiler | AdvancedProfiler | False
  dir: /home/nfs/jlhofland/debugging
  accelerator: False
  batch_tuner: False
  anomaly: False
model:
  name: cubicasa
  input_slice: [21, 12, 11]
  loss: uncertainty
  weights: False # path | False
optimizer:
  name: adam
  lr: 0.001
  eps: 1e-08
  betas: [0.9, 0.999]
  patience: 10
train:
  batch_size: 20
  accumulate_grad_batches: 1 # effective batch size = accumulate_grad_batches * batch_size
  resume: False # path | False
  max_epochs: 100
  max_time:
    enable: False
    days: 0
    hours: 0
    minutes: 0
  debug:
    enable: False
    print: False
    train_batches: 50 # number | False
    val_batches: 50 # number | False
    test_batches: 50 # number | False
dataset:
  name: cubicasa
  num_workers: 8 # 10 (local) | 0.5 * cpus (cluster)
  format: txt # lmdb or txt
  augmentations: True
  original_size: True
  persistent_workers: True
  pin_memory: True
  grayscale: True
  load_ram: False
  save_samples: False
  load_samples: True
  scale: True
  image_size: 256
  files:
    root: /tudelft.net/staff-umbrella/StudentsCVlab/jlhofland
    train: train_hqa_hq.txt
    val: val_hqa_hq.txt
    test: test_c.txt