seed: 0
wandb:
  log: True
  dir: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\runs_new
  experiment_name: TEST_METRICS
  entity: hofland-jeroen
  project: cc5k
debugger:
  batches: False # number | False
  profiler: SimpleProfiler # SimpleProfiler | AdvancedProfiler | False
  dir: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\debugging
  accelerator: False
  batch_tuner: False
  anomaly: False
model:
  name: CubiCasa # CubiCasaMMD | CubiCasa | False
  input_slice: [21, 12, 11]
  loss: UncertaintyLoss # UncertaintyLoss | False
  use_mmd: True
  weights: False # path | False
optimizer:
  name: adam
  lr: 0.001
  eps: 1e-08
  betas: [0.9, 0.999]
  patience: 10
train:
  batch_size: 8
  accumulate_grad_batches: 1 # effective batch size = accumulate_grad_batches * batch_size
  resume: False # path | False
  max_epochs: 2
  max_time:
    enable: False
    days: 0
    hours: 0
    minutes: 0
  debug:
    enable: False
    print: False
    train_batches: 50 # number | False
    val_batches: 50 # number | False
    test_batches: 50 # number | False
test:
  weights: False # path | False
  data: test_hqa.txt
dataset:
  name: cubicasa
  num_workers: 4 # 10 (local) | 0.5 * cpus (cluster)
  format: txt # lmdb or txt
  augmentations: True
  original_size: True
  persistent_workers: True
  pin_memory: True
  grayscale: False
  overwrite: False
  save_samples: False
  load_samples: True
  scale: True
  image_size: 256
  files:
    root: C:\Users\j.a.hofland\Documents\thesis-coding\pytorch-lightning-example\data\
    train: train_hqa_hq.txt
    val: val_hqa_hq.txt
    mmd:
      train: train_c.txt
      val: val_c.txt
    test: 
      d1: test_hqa.txt
      d2: test_hq.txt
      d3: test_c.txt