seed: 0
wandb:
  log: true
  dir: /home/nfs/jlhofland/runs
  experiment_name: TRAIN_100E_400E_B20_32W
  entity: hofland-jeroen
  project: cc5k
debugger:
  batches: False # number | False
  profiler: SimpleProfiler # SimpleProfiler | AdvancedProfiler | False
  accelerator: False
  batch_tuner: False
  anomaly: False
model:
  name: cubicasa
  input_slice: [21, 12, 11]
  loss: uncertainty
  weights: False # path | False
optimizer:
  name: adam
  lr: 0.001
  eps: 1e-08
  betas: [0.9, 0.999]
  patience: 10
train:
  batch_size: 20
  accumulate_grad_batches: 1 # effective batch size = accumulate_grad_batches * batch_size
  resume: /home/nfs/jlhofland/weights/model-4.ckpt # path | False
  max_epochs: 400
  max_time:
    enable: False
    days: 0
    hours: 23
    minutes: 0
  debug:
    enable: False
    print: False
    train_batches: 50 # number | False
    val_batches: 50 # number | False
    test_batches: 50 # number | False
dataset:
  name: cubicasa
  num_workers: 8 # 0 (windows) | #cpus (linux)
  format: txt # lmdb or txt
  augmentations: True
  scale: False
  image_size: 256
  files:
    root: /default/
    train: train_hqa_hq.txt
    val: val_hqa_hq.txt
    test: test_c.txt