name: fp-vector
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - omegaconf=2.3.0
  - python=3.10
  - pytorch=2.2.1
  - cudatoolkit=11.8
  - pytorch-lightning=2.2.0
  - torchvision=0.17.1
  - wandb=0.16.3
  - torchmetrics=1.3.1
  - svgpathtools=1.6.1
  - shapely=2.0.2
  - scikit-image=0.22.0
  - matplotlib=3.8.2
  - opencv-python=4.9.0.80
  - tqdm=4.66.1
  - torchaudio=2.2.1
  - python-lmdb
