name: pytorch-lightning-example
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - omegaconf=2.3.0
  - python=3.11
  - pytorch
  - cudatoolkit=12.3
  - pytorch-lightning=2.2.0
  - torchvision=0.17.1
  - wandb=0.16.3
